config/routes.rb
Rails.application.routes.draw do
  get    "tasks",          to: "tasks#index"

  get    "tasks/new",      to: "tasks#new"
  post   "tasks",          to: "tasks#create"

  get    "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch  "tasks/:id",      to: "tasks#update"

  get    "tasks/:id",      to: "tasks#show", as: :task

  delete "tasks/:id",      to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :done? %>
  <%= label :done, 'Yes' %>
  <%= f.radio_button :done, true %>
  <%= label :done, 'No' %>
  <%= f.radio_button :done, false, :checked => true %>
  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks list</h1>

<% @tasks.each do |task| %>
  <% status = task.done ? 'Done' : 'Not done' %>
  <p>
    <strong><%= task.description %>: </strong><%= status %>
    <%= link_to "Show", task_path(task) %>
    <%= link_to "Edit", edit_task_path(task) %>
    <%= link_to "Delete", task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
  </p>
<% end %>

<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<% status = @task.done ? 'Done' : 'Not done' %>
<h2><%= @task.description.upcase %></h2>
<p>Status: <%= status %></p>
<p>Created at <%= @task.created_at %></p>

<%= link_to "Home", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>